### ISSUE TITLE
Automatically update CDN URLs in README for major release

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/release-action#1]
Upon a major release, [the CDN URLs in the README](https://github.com/simple-icons/simple-icons/blob/develop/README.md#cdn-usage) should be updated to match the new major version.

As per [my comment](https://github.com/simple-icons/release-action/issues/1#issuecomment-782190710), this should probably be implemented through the main project's [Create release workflow](https://github.com/simple-icons/simple-icons/blob/1dcec241332b77b7c8a4dd3e18835c6eafb878ac/.github/workflows/create-release.yml#L18) with a local script similar to [the `build-slugs-table.js` script](https://github.com/simple-icons/simple-icons/blob/1dcec241332b77b7c8a4dd3e18835c6eafb878ac/scripts/build-slugs-table.js).

Leaving this open here for now so we don't forget about the issue.

**Comment by PeterShaggyNoble** [comment]
Would it also be possible, as per [my comment here](simple-icons/simple-icons#4507), to have it update the icon count every time we pass the next 500 icon "milestone"?

**Comment by ericcornelissen** [comment]
Given the current changes of https://github.com/simple-icons/simple-icons/pull/5002, we might be able to resolve this issue in [the simple-icons repository](https://github.com/simple-icons/simple-icons) itself.
