### ISSUE TITLE
Pull requests with meta labels must be merged latest

### ISSUE THREAD

**Issue by mondeja** [simple-icons/release-action#10]
[Pull of latest release](https://github.com/simple-icons/simple-icons/pull/3085) have been failed because an icon has been merged after a pull with `meta` label:
- mondeja Fix 'wslint' command that isn't linting the simple-icons.json file. (`#3079`)
- PeterShaggyNoble Update Adobe Creative Cloud (`#3032`)

Meta pulls are capable of change linting or testing restrictions, so must be merged latest?

**Comment by ericcornelissen** [comment]
Thanks for trying to help out @mondeja but 1) this action is not the place the solve that issue and 2) I don't think there is a way to enforce this properly, there is no way to merge them last as there is always other Pull Requests that can be merged. If the build on `develop` fails, that is not a problem, it just tells us that something is wrong that needs to be changed. Yes, changes like that will result in a transition period, but that's fine.
