### ISSUE TITLE
Accidental change detected in data file diff

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/release-action#16]
From https://github.com/simple-icons/simple-icons/pull/2951 the release action thinks Flattr has been updated (as demonstrated by the original release notes of https://github.com/simple-icons/simple-icons/pull/3105)

**Comment by PeterShaggyNoble** [comment]
Could this be resolved by parsing the JSON and comparing values?

**Comment by ericcornelissen** [comment]
It definitely would. I need to look into how doable that is though. But it's definitely a good suggestion, thanks :smile:

**Comment by mondeja** [comment]
Could this be obsolete after [simple-icons/simple-icons/#4320](https://github.com/simple-icons/simple-icons/pull/4320)?

**Comment by ericcornelissen** [comment]
I'd say so yes, thanks @mondeja

<sup>Though there are probably still ways the diff can confuse this Action, but we can track that in a separate issue when it arises</sup>
