### ISSUE TITLE
Different casing messes up alphabetical ordering

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/release-action#17]
#15 implemented a simple feature that orders changes based on the brand name, however, as demonstrated by https://github.com/simple-icons/simple-icons/pull/3105 this implementation does not work if there are brands with different casing. In this release a brand named "pandas" (lowercase "p") appears last in the list of new icons, after (among others) "Wistia" (uppercase "W").

**Comment by PeterShaggyNoble** [comment]
Looks like we may also have [a similar issue](https://stackoverflow.com/questions/44740602/how-can-the-lodash-orderby-function-be-made-to-work-with-accented-characters) with accented characters so I think the solution here might need to be to replace the accented characters in the `["name"]` object and then convert it to lowercase. Or use a regular JS `sort` with `localeCompare`.

**Comment by ericcornelissen** [comment]
I think we should be able to resolve this issue without simplifying the character est of the `"name"` property (e.g. with `localCompare`). Thanks for the suggestions :+1:

**Comment by ericcornelissen** [comment]
Surprisingly, the sorting already handled accented brand names correctly (at least the ones I tested on my local machine).

In any case, #18 should fix any issues related to this.
