### ISSUE TITLE
Automatically update "milestone" (SVG count) in README

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/release-action#27]
As per @PeterShaggyNoble's [comment here](https://github.com/simple-icons/simple-icons/pull/4507#issuecomment-756879683), have the Action update the icon count every time we pass the next 500 icon "milestone".

If we are going to automate it anyway, maybe we can do it every 100? 

~~For anyone looking to implement this, don't forget that it should probably also be lowered automatically!~~

As per [my comment](https://github.com/simple-icons/release-action/issues/27#issuecomment-782190856), this should probably be implemented through the main project's [Create release workflow](https://github.com/simple-icons/simple-icons/blob/1dcec241332b77b7c8a4dd3e18835c6eafb878ac/.github/workflows/create-release.yml#L18) with a local script similar to [the `build-slugs-table.js` script](https://github.com/simple-icons/simple-icons/blob/1dcec241332b77b7c8a4dd3e18835c6eafb878ac/scripts/build-slugs-table.js).

Leaving this open here for now so we don't forget about the issue.

**Comment by PeterShaggyNoble** [comment]
Of course, the logical follow-up question would be: if we are going to automate it anyway, we may as well use the exact count.

Personally, from a marketing point of view, I prefer the "Over _X_" phrasing, though - "Over 1500" sounds better than "1501".

**Comment by ericcornelissen** [comment]
> Of course, the logical follow-up question would be: if we are going to automate it anyway, we may as well use the exact count.
> 
> Personally, from a marketing point of view, I prefer the "Over _X_" phrasing, though - "Over 1500" sounds better than "1501".

I agree, which is why I didn't suggest it :upside_down_face:

**Comment by ericcornelissen** [comment]
Given the current changes of https://github.com/simple-icons/simple-icons/pull/5002, we might be able to resolve this issue in [the simple-icons repository](https://github.com/simple-icons/simple-icons) itself.
