### ISSUE TITLE
Remove 'create.js' exports, testing the task by integration

### ISSUE THREAD

**Issue by mondeja** [simple-icons/release-action#28]
[Function exports in `src/create.js`](https://github.com/simple-icons/release-action/blob/0d6c88dbdfd9387eccab63b36f6efa48194531ea/src/create.js#L583-L588) are currently a bit hacky because are setted as properties of `makeRelease` function. As @ericcornelissen [suggested](https://github.com/simple-icons/release-action/pull/24#issuecomment-756937409), these should not be exported, but the testing must be done integrating the whole task.

**Comment by ericcornelissen** [comment]
Fixed in e71dfc05ccdb7657687a73f835f46b2e649dde16
