### ISSUE TITLE
Does not take into account changes in icons SVGs newlines

### ISSUE THREAD

**Issue by mondeja** [simple-icons/release-action#69]
See [this](https://github.com/simple-icons/simple-icons/pull/7020/files#diff-772ff27a31d81698bc1238d92428165939f70f31bb3039e4735ddc69243b51af), has been added a newline to the SVG but this should not be marked as updated.

**Comment by PeterShaggyNoble** [comment]
We don't allow newlines in the SVGs, so this shouldn't be a problem.
